apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
  namespace: default

---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  namespace: default
  name: vault-auth
  annotations:
    kubernetes.io/service-account.name: "vault-auth"
