# apiVersion: external-secrets.io/v1beta1
# kind: SecretStore
# metadata:
#   name: vault
# spec:
#   provider:
#     vault:
#       server: "https://vault.int.nai.nu:8200"
#       path: "kv/talos"
#       version: "v2"
#       auth:
#         kubernetes:
#           mountPath: "talos"
#           role: "talos"
#           serviceAccountRef:
#             name: "vault-auth"
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault
  namespace: external-secrets
spec:
  provider:
    vault:
      server: "https://vault.int.nai.nu:8200"
      path: "kv/talos"
      # Version is the Vault KV secret engine version.
      # This can be either "v1" or "v2", defaults to "v2"
      version: "v2"
      auth:
        # points to a secret that contains a vault token
        # https://www.vaultproject.io/docs/auth/token
        tokenSecretRef:
          name: "vault-token"
          key: "token"
          namespace: "external-secrets"