apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-issuer-prod
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  acme:
    email: robin.runesson@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: le-clusterissuer-privatekey
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-config
              key: api-token
