apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-config
  namespace: cert-manager
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: vault
  target:
    name: cloudflare-config
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: cert-manager/cloudflare-config
