apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/cert-manager/cert-manager/releases/download/v1.16.2/cert-manager.crds.yaml
  - cert-manager-helm.yaml
  - external-secret.yaml
  - clusterissuer-prod.yaml
  - ../../bases/secretstore

transformers:
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: abc123
      namespace: cert-manager
    unsetOnly: true
