apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # - https://raw.githubusercontent.com/sergelogvinov/proxmox-csi-plugin/main/docs/deploy/proxmox-csi-plugin.yml
  - csi-proxmox-helm.yaml
  # - ../../bases/secretstore
  - proxmox-config.yaml
  - csi-proxmox-ns.yaml

transformers:
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: abc123
      namespace: csi-proxmox
    unsetOnly: true
