apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/rbnrun/homelab-gitops
      revision: master
      directories:
      - path: core/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 15
          backoff:
            duration: 15s
            factor: 2
            maxDuration: 5m
        syncOptions:
          - SkipDryRunOnMissingResource=true
      source:
        repoURL: https://github.com/rbnrun/homelab-gitops
        targetRevision: master
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
