apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../bootstrap/overlays/default/
  - ../../bases/traefik-redirect
  - ../../bases/secretstore
  - ingress.yaml
  - oidc-secret.yaml
  - truecharts-repo.yaml

patches:
  - path: cmd-params-cm.yaml
    target:
      kind: ConfigMap
      name: argocd-cmd-params-cm
  # - path: argocd-cm.yaml
  #   target:
  #     kind: ConfigMap
  #     name: argocd-cm
  # - path: argocd-rbac-cm.yaml
  #   target:
  #     kind: ConfigMap
  #     name: argocd-rbac-cm

transformers:
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: abc123
      namespace: argocd
    unsetOnly: true