apiVersion: v1
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: truecharts-helm-oci
  namespace: argocd
stringData:
  url: tccr.io/truecharts/
  name: truecharts
  type: helm
  enableOCI: "true"
